services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch-815
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data_815:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.0
    container_name: logstash-815
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana-815
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.0
    container_name: filebeat-815
    depends_on:
      - logstash
    user: root
    command: [ "filebeat", "-e", "--strict.perms=false" ]
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      # üëá ƒê∆Ø·ªúNG D·∫™N HOST TH·∫¨T ƒê·∫æN TH∆Ø M·ª§C logs C·ª¶A BE
      - "F:/Khank_Sky/HAU/DoAn/mangmt/mini-social/social-be/logs:/usr/share/application/logs:ro"

  mysql:
    image: mysql:8.0
    container_name: mysql-8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "social"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "123456"
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  es_data_815:
  mysql_data:
